const CONFIG={business:"Aquí podría ir el nombre de tu consultorio",address:"Aquí iría tu ubicación",mapUrl:"https://www.google.com/maps/search/?api=1&query=Centro+Guadalajara+Jalisco",bank:"Aquí podrían ir tus datos bancarios",storage:"demoFisioAppointments"};
const SERVICES=[
{id:"assessment_initial",area:"hands",name:"Valoración inicial",minutes:60,price:0},
{id:"assessment_followup",area:"hands",name:"Consulta de seguimiento",minutes:45,price:0},
{id:"assessment_functional",area:"hands",name:"Evaluación funcional y postural",minutes:60,price:0},
{id:"therapy_musculoskeletal",area:"feet",name:"Fisioterapia musculoesquelética",minutes:60,price:0},
{id:"therapy_sports",area:"feet",name:"Rehabilitación deportiva",minutes:60,price:0},
{id:"therapy_postoperative",area:"feet",name:"Rehabilitación postoperatoria",minutes:60,price:0},
{id:"therapy_neurological",area:"feet",name:"Fisioterapia neurológica",minutes:60,price:0},
{id:"therapy_geriatric",area:"feet",name:"Fisioterapia geriátrica",minutes:60,price:0},
{id:"therapy_manual",area:"feet",name:"Terapia manual",minutes:60,price:0},
{id:"therapy_massage",area:"feet",name:"Masaje terapéutico",minutes:60,price:0},
{id:"therapy_dry_needling",area:"feet",name:"Punción seca",minutes:45,price:0},
{id:"therapy_home",area:"feet",name:"Rehabilitación a domicilio",minutes:90,price:0}
];
const WEEKDAY_TIMES=["10:30","12:30","16:00","18:00"],SATURDAY_TIMES=["10:00","11:30"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={services:[],date:null,time:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const views={home:$("#inicio"),booking:$("#bookingView"),confirmation:$("#confirmationView"),admin:$("#adminView"),agenda:$("#agendaView")};
const pad=n=>String(n).padStart(2,"0");
const toISO=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const fromISO=s=>{const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
const prettyDate=s=>fromISO(s).toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
const timesForDate=date=>{const day=fromISO(date).getDay();return day===0?[]:day===6?SATURDAY_TIMES:WEEKDAY_TIMES};
const money=n=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(n);
const escapeHTML=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const phone=v=>String(v).replace(/\D/g,"");
const appointments=()=>{try{return JSON.parse(localStorage.getItem(CONFIG.storage))||[]}catch{return[]}};
let cloudBusy=[];
const save=list=>{const before=appointments(),beforeById=new Map(before.map(item=>[item.id,item])),afterIds=new Set(list.map(item=>item.id));localStorage.setItem(CONFIG.storage,JSON.stringify(list));list.forEach(item=>{const old=beforeById.get(item.id);if(!old||old.updatedAt!==item.updatedAt)window.CloudAppointments?.upsert(item).catch(()=>{})});before.forEach(item=>{if(!afterIds.has(item.id))window.CloudAppointments?.remove(item.id).catch(()=>{})})};
const service=id=>SERVICES.find(item=>item.id===id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
function showView(name){Object.values(views).forEach(v=>v.hidden=true);views[name].hidden=false;scrollTo({top:0,behavior:"smooth"})}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2500)}
function waLink(number,message){const digits=phone(number);const international=digits.length===10?`52${digits}`:digits;return `https://wa.me/${international}?text=${encodeURIComponent(message)}`}
function openWhatsApp(number,message){window.open(waLink(number,message),"_blank","noopener,noreferrer")}

function renderServices(){$("#serviceGrid").innerHTML=SERVICES.map(s=>`<button class="service-card${state.services.includes(s.id)?" selected":""}" data-service="${s.id}"><strong>${s.name}</strong><small>${s.area==="feet"?"Tratamiento":"Valoración y consulta"}</small><span class="service-meta"><span>${s.minutes} min</span><span>${s.price?`Desde ${money(s.price)}`:"Precio por confirmar"}</span></span></button>`).join("");renderSelectedServices()}
function renderSelectedServices(){const selected=state.services.map(service).filter(Boolean),wrap=$("#selectedServices");wrap.hidden=!selected.length;$("#selectedServiceList").innerHTML=selected.map(s=>`<div class="selected-service-item"><div><strong>${escapeHTML(s.name)}</strong><span> · ${s.area==="feet"?"Tratamiento":"Valoración"}</span></div><button type="button" data-remove-service="${s.id}">Quitar</button></div>`).join("")}
function toggleService(id){state.services=state.services.includes(id)?state.services.filter(value=>value!==id):[...state.services,id];state.date=null;state.time=null;renderServices();$("#dateStep").classList.toggle("is-locked",!state.services.length);$("#detailsStep").classList.add("is-locked");$("#timesWrap").hidden=true;renderCalendar();renderSummary();if(state.services.length)$("#dateStep").scrollIntoView({behavior:"smooth",block:"center"})}
function renderCalendar(){const cal=$("#calendar"),year=state.month.getFullYear(),month=state.month.getMonth(),today=new Date();today.setHours(0,0,0,0);$("#monthLabel").textContent=state.month.toLocaleDateString("es-MX",{month:"long",year:"numeric"});cal.innerHTML="";const first=new Date(year,month,1).getDay(),offset=first===0?6:first-1;for(let i=0;i<offset;i++)cal.append(document.createElement("span"));const total=new Date(year,month+1,0).getDate();for(let day=1;day<=total;day++){const date=new Date(year,month,day),iso=toISO(date),btn=document.createElement("button");btn.className=`day-btn${state.date===iso?" selected":""}`;btn.textContent=day;btn.disabled=date<today||date.getDay()===0; if(!btn.disabled){btn.classList.add("available");btn.onclick=()=>selectDate(iso)}cal.append(btn)}}
function selectDate(iso){state.date=iso;state.time=null;renderCalendar();renderTimes();renderSummary()}
function availableTimes(date,ignoreId=""){const occupied=[...appointments().filter(a=>a.date===date&&a.id!==ignoreId).map(a=>a.time),...cloudBusy.filter(a=>a.date===date).map(a=>a.time)];return timesForDate(date).filter(t=>!occupied.includes(t))}
function renderTimes(){const wrap=$("#timesWrap"),grid=$("#timeGrid");wrap.hidden=false;$("#selectedDateLabel").textContent=`Horarios para ${prettyDate(state.date)}`;const times=availableTimes(state.date);grid.innerHTML=times.length?times.map(t=>`<button class="time-btn${state.time===t?" selected":""}" data-time="${t}">${t}</button>`).join(""):`<p class="time-empty">No quedan horarios disponibles ese día.</p>`}
function selectTime(time){state.time=time;renderTimes();$("#detailsStep").classList.remove("is-locked");renderSummary();$("#detailsStep").scrollIntoView({behavior:"smooth",block:"center"})}
function renderSummary(){const box=$("#liveSummary"),selected=state.services.map(service).filter(Boolean);if(!selected.length){box.className="empty-summary";box.textContent="Selecciona uno o varios servicios para comenzar.";return}const minutes=selected.reduce((total,item)=>total+item.minutes,0),knownPrices=selected.filter(item=>item.price),price=knownPrices.reduce((total,item)=>total+item.price,0),hasPending=knownPrices.length!==selected.length;box.className="";box.innerHTML=`<h4>${selected.length===1?escapeHTML(selected[0].name):`${selected.length} servicios`}</h4>${selected.map(s=>`<div class="summary-row"><span>${s.area==="feet"?"Tratamiento":"Valoración"}</span><strong>${escapeHTML(s.name)}</strong></div>`).join("")}<div class="summary-row"><span>Duración estimada</span><strong>${minutes} min</strong></div><div class="summary-row"><span>Fecha</span><strong>${state.date?escapeHTML(prettyDate(state.date)):"Por elegir"}</strong></div><div class="summary-row"><span>Hora</span><strong>${state.time||"Por elegir"}</strong></div><div class="summary-row summary-total"><span>Precio</span><strong>${price?`Desde ${money(price)}${hasPending?" + por confirmar":""}`:"Por confirmar"}</strong></div>`}
function resetBooking(){Object.assign(state,{services:[],date:null,time:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)});$("#bookingForm").reset();$("#dateStep").classList.add("is-locked");$("#detailsStep").classList.add("is-locked");$("#timesWrap").hidden=true;renderServices();renderCalendar();renderSummary()}
function confirmationMessage(a){const labels=(a.services||[{id:a.serviceId}]).map(entry=>service(entry.id)?.name).filter(Boolean).join(", ");return `¡Hola, ${a.name}! 💅\n\nGracias por agendar en ${CONFIG.business}.\n\n📅 ${prettyDate(a.date)}\n🕐 ${a.time} h\n✨ ${labels}\n📍 ${CONFIG.address}\n\nTe recordamos nuestras políticas:\n• Para cancelar o reagendar, avísanos con al menos 48 horas de anticipación.\n• Después de 10 minutos de retraso, la cita será cancelada y el anticipo no será reembolsable.\n• Los anticipos no son reembolsables; avisando con al menos 48 horas de anticipación, pueden conservarse para una nueva fecha.\n• Una cita puede reagendarse un máximo de dos veces.\n\n¡Te esperamos!`}
function createAppointment(event){event.preventDefault();const name=$("#clientName").value.trim(),number=phone($("#clientPhone").value),accepted=$("#policyCheck").checked,error=$("#formError"),selected=state.services.map(service).filter(Boolean);if(!name||number.length<10||!accepted){error.textContent="Completa tu nombre, un WhatsApp válido y acepta las políticas.";return}if(!selected.length||!state.date||!state.time){error.textContent="Selecciona al menos un servicio, fecha y hora.";return}if(!availableTimes(state.date).includes(state.time)){error.textContent="Ese horario acaba de ocuparse. Elige otro, por favor.";renderTimes();return}const services=selected.map(item=>({id:item.id,area:item.area,mode:"",finish:""})),areas=new Set(services.map(item=>item.area)),area=areas.size>1?"both":services[0].area,first=services[0],firstHand=services.find(item=>item.area==="hands"),firstFoot=services.find(item=>item.area==="feet"),now=new Date().toISOString(),item={id:uid(),name,phone:number,area,services,serviceId:first.id,feetServiceId:firstFoot?.id||"",mode:firstHand?.mode||"",finish:firstHand?.finish||"",feetMode:firstFoot?.mode||"",feetFinish:firstFoot?.finish||"",date:state.date,time:state.time,price:selected.reduce((total,item)=>total+item.price,0),deposit:0,status:"Programada",reschedules:0,notes:$("#clientNotes").value.trim(),createdAt:now,updatedAt:now};const list=appointments();list.push(item);save(list);$("#confirmationSummary").innerHTML=`${selected.map(s=>`<div class="summary-row"><span>${s.area==="feet"?"Tratamiento":"Valoración"}</span><strong>${escapeHTML(s.name)}</strong></div>`).join("")}<div class="summary-row"><span>Fecha</span><strong>${prettyDate(item.date)}</strong></div><div class="summary-row"><span>Hora</span><strong>${item.time} h</strong></div><div class="summary-row"><span>WhatsApp</span><strong>${escapeHTML(item.phone)}</strong></div><div class="summary-row"><span>Ubicación</span><strong>${escapeHTML(CONFIG.address)}</strong></div>`;showView("confirmation")}

function renderAdmin(){const date=$("#adminDate").value,list=appointments().filter(a=>a.date===date).sort((a,b)=>a.time.localeCompare(b.time));$("#appointmentList").innerHTML=list.length?list.map(a=>`<article class="appointment-item"><div class="appointment-time">${a.time} h</div><div><span class="status">Confirmada</span><h3>${escapeHTML(a.name)}</h3><p>${escapeHTML(service(a.serviceId)?.name||"Servicio")} · ${escapeHTML(a.phone)}</p>${a.notes?`<p>“${escapeHTML(a.notes)}”</p>`:""}</div><button class="secondary-btn" data-edit="${a.id}">Ver y editar</button></article>`).join(""):`<div class="empty-state">No hay citas registradas para este día.</div>`}
function fillEditTimes(selected,ignoreId){$("#editTime").innerHTML=availableTimes($("#editDate").value,ignoreId).concat(selected&&!availableTimes($("#editDate").value,ignoreId).includes(selected)?[selected]:[]).sort().map(t=>`<option value="${t}"${t===selected?" selected":""}>${t} h</option>`).join("")}
function openEdit(id){const a=appointments().find(x=>x.id===id);if(!a)return;$("#editId").value=a.id;$("#editName").value=a.name;$("#editPhone").value=a.phone;$("#editService").value=a.serviceId;$("#editDate").value=a.date;$("#editNotes").value=a.notes||"";fillEditTimes(a.time,a.id);$("#appointmentDialog").showModal()}
function saveEdit(e){e.preventDefault();const list=appointments(),index=list.findIndex(a=>a.id===$("#editId").value);if(index<0)return;list[index]={...list[index],name:$("#editName").value.trim(),phone:phone($("#editPhone").value),serviceId:$("#editService").value,date:$("#editDate").value,time:$("#editTime").value,notes:$("#editNotes").value.trim(),updatedAt:new Date().toISOString()};save(list);$("#appointmentDialog").close();$("#adminDate").value=list[index].date;renderAdmin();toast("Cita actualizada")}
function cancelAppointment(){const id=$("#editId").value;if(!confirm("¿Quieres cancelar y eliminar esta cita?"))return;save(appointments().filter(a=>a.id!==id));$("#appointmentDialog").close();renderAdmin();toast("Cita cancelada")}

$("#serviceGrid").addEventListener("click",e=>{const b=e.target.closest("[data-service]");if(b)toggleService(b.dataset.service)});$("#selectedServiceList").addEventListener("click",e=>{const b=e.target.closest("[data-remove-service]");if(b)toggleService(b.dataset.removeService)});$("#timeGrid").addEventListener("click",e=>{const b=e.target.closest("[data-time]");if(b)selectTime(b.dataset.time)});$("#bookingForm").addEventListener("submit",createAppointment);
function showPublicSite(){$("#publicHeader").hidden=false;document.querySelector("footer").hidden=false;showView("home")}
function loadAgenda(){const host=$("#agendaView");if(host.shadowRoot){window.refreshAgenda?.();return}const template=$("#agendaTemplate");template.innerHTML=template.innerHTML.replaceAll("agenda/css/styles.css","agenda/css/styles.css?v=fisio2").replaceAll("agenda/css/brand.css","agenda/css/brand.css?v=fisio2").replaceAll("Hola, bienvenida.","Hola, bienvenido.").replaceAll("Nombre de la clienta","Nombre del paciente").replaceAll("la clienta","el paciente").replaceAll("cada clienta","cada paciente").replaceAll("Manos y pies","Valoración y tratamiento").replaceAll(">Manos<",">Valoración y consulta<").replaceAll(">Pies<",">Tratamiento<").replaceAll("Diseño, color o cualquier detalle","Motivo de consulta, molestias, diagnóstico o indicaciones");const root=host.attachShadow({mode:"open"});root.append(template.content.cloneNode(true));const area=root.querySelector("#areaSelect");if(area){area.options[0].textContent="Valoración y consulta";area.options[1].textContent="Tratamiento";area.options[2].textContent="Valoración y tratamiento"}window.__agendaRoot=root;window.__agendaClose=showPublicSite;root.querySelectorAll(".embedded-back").forEach(button=>button.onclick=showPublicSite);const script=document.createElement("script");script.type="module";script.src="agenda/js/app.js?v=fisio2";document.head.append(script)}
function openSecureAgenda(){loadAgenda();$("#publicHeader").hidden=true;document.querySelector("footer").hidden=true;showView("agenda")}
$("#adminBtn").onclick=event=>{event.preventDefault();if(window.CloudAppointments?.isUnlocked()){openSecureAgenda();return}$("#adminAccessError").textContent="";$("#adminAccessForm").reset();$("#adminAccessDialog").showModal();setTimeout(()=>$("#adminAccessKey").focus(),50)};
$("#adminAccessForm").onsubmit=async event=>{event.preventDefault();const submit=event.submitter,error=$("#adminAccessError");error.textContent="";submit.disabled=true;submit.textContent="Comprobando…";try{await window.CloudAppointments?.unlock($("#adminAccessKey").value);$("#adminAccessDialog").close();openSecureAgenda()}catch{error.textContent="La clave de acceso no es correcta."}finally{submit.disabled=false;submit.textContent="Entrar a Mi agenda"}};
$("#startBookingBtn").onclick=()=>{resetBooking();showView("booking")};$$('[data-go-home]').forEach(b=>b.onclick=()=>showView("home"));
$("#prevMonth").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$("#nextMonth").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};
$("#showPoliciesBtn").onclick=()=>$("#policiesDialog").showModal();$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest("dialog").close());$("#openLocationBtn").onclick=()=>window.open(CONFIG.mapUrl,"_blank","noopener,noreferrer");
$("#todayBtn").onclick=()=>{$("#adminDate").value=toISO(new Date());renderAdmin()};$("#adminDate").onchange=renderAdmin;$("#appointmentList").onclick=e=>{const b=e.target.closest("[data-edit]");if(b)openEdit(b.dataset.edit)};$("#editDate").onchange=()=>fillEditTimes("",$("#editId").value);$("#editForm").onsubmit=saveEdit;$("#cancelAppointmentBtn").onclick=cancelAppointment;
$("#paymentBtn").onclick=()=>$("#paymentDialog").showModal();$("#paymentForm").onsubmit=e=>{e.preventDefault();const number=phone($("#paymentPhone").value);if(number.length<10){toast("Escribe un número válido");return}openWhatsApp(number,`Hola 👋 Te compartimos los datos para transferencia de ${CONFIG.business}:\n\n${CONFIG.bank}\n\nCuando realices tu transferencia, por favor envíanos tu comprobante. Gracias 💅`);$("#paymentDialog").close()};
$("#editService").innerHTML=SERVICES.map(s=>`<option value="${s.id}">${s.name}</option>`).join("");renderServices();renderCalendar();renderSummary();window.CloudAppointments?.hydrateAvailability(list=>{cloudBusy=list}).then(()=>{renderCalendar();renderSummary()});
