const SPREADSHEET_ID="16vWCXhUfLStcgcnIPNwlRFQ7MW3zwaUBDa_NZXfEqN0",SHEET_NAME="Agenda Fisioterapia Demo",ACCESS_KEY_PROPERTY="AGENDA_FISIOTERAPIA_ACCESS_KEY";
const HEADERS=["ID","Fecha","Hora","Paciente","WhatsApp","Área","Servicios","Duración (min)","Precio","Anticipo","Saldo","Estado","Reprogramaciones","Notas","Creada","Actualizada","Origen","Datos JSON"];
function setupAgendaFisioterapia(){const s=getSheet_();s.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);s.setFrozenRows(1);const p=PropertiesService.getScriptProperties();let k=p.getProperty(ACCESS_KEY_PROPERTY);if(!k){k=Utilities.getUuid().replace(/-/g,"");p.setProperty(ACCESS_KEY_PROPERTY,k)}console.log(`AGENDA_FISIOTERAPIA_ACCESS_KEY=${k}`);return k}
function doGet(e){const p=e?.parameter||{};if(!authorized_(p.key))return response_({ok:false,error:"Acceso no autorizado"},p.callback);if(p.action!=="list")return response_({ok:false,error:"Acción no válida"},p.callback);const l=LockService.getScriptLock();l.waitLock(10000);try{return response_({ok:true,appointments:readAppointments_()},p.callback)}finally{l.releaseLock()}}
function doPost(e){const p=e?.parameter||{};if(!authorized_(p.key))return response_({ok:false,error:"Acceso no autorizado"});let data;try{data=JSON.parse(p.payload||"null")}catch(x){return response_({ok:false,error:"Datos inválidos"})}const l=LockService.getScriptLock();l.waitLock(10000);try{if(p.action==="upsert")upsert_(data);else if(p.action==="delete")remove_(data?.id);else if(p.action==="replace")replace_(data);else return response_({ok:false,error:"Acción no válida"});return response_({ok:true})}finally{l.releaseLock()}}
function getSheet_(){const b=SpreadsheetApp.openById(SPREADSHEET_ID);return b.getSheetByName(SHEET_NAME)||b.insertSheet(SHEET_NAME)}
function authorized_(k){const e=PropertiesService.getScriptProperties().getProperty(ACCESS_KEY_PROPERTY);return Boolean(e&&k&&k===e)}
function readAppointments_(){const s=getSheet_(),n=s.getLastRow();if(n<2)return[];return s.getRange(2,18,n-1,1).getDisplayValues().flat().filter(Boolean).map(v=>{try{return JSON.parse(v)}catch(x){return null}}).filter(Boolean)}
function upsert_(a){if(!a?.id)throw new Error("La cita no tiene ID");const s=getSheet_(),n=s.getLastRow();let r=n+1;if(n>=2){const i=s.getRange(2,1,n-1,1).getDisplayValues().flat().indexOf(String(a.id));if(i>=0)r=i+2}s.getRange(r,1,1,HEADERS.length).setValues([row_(a)])}
function remove_(id){if(!id)return;const s=getSheet_(),n=s.getLastRow();if(n<2)return;const i=s.getRange(2,1,n-1,1).getDisplayValues().flat().indexOf(String(id));if(i>=0)s.deleteRow(i+2)}
function replace_(a){if(!Array.isArray(a))throw new Error("Respaldo inválido");const s=getSheet_(),n=s.getLastRow();if(n>1)s.getRange(2,1,n-1,HEADERS.length).clearContent();if(a.length)s.getRange(2,1,a.length,HEADERS.length).setValues(a.map(row_))}
function row_(a){const areas={hands:"Valoración",feet:"Tratamiento",both:"Valoración y tratamiento"},sv=Array.isArray(a.services)?a.services:[],labels=sv.map(x=>[x.area==="feet"?"Tratamiento":"Valoración",x.name||x.id].filter(Boolean).join(" · ")).join(" | "),duration=sv.reduce((t,x)=>t+(Number(x.minutes)||0),0),price=Number(a.price)||0,deposit=Number(a.deposit)||0;return[a.id||"",a.date||"",a.time||"",a.name||"",a.phone||"",areas[a.area]||a.area||"",labels,duration,price,deposit,Math.max(price-deposit,0),a.status||"Programada",Number(a.reschedules)||0,a.notes||"",a.createdAt||"",a.updatedAt||"","Agenda Fisioterapia",JSON.stringify(a)]}
function response_(p,c){const j=JSON.stringify(p);if(c&&/^[A-Za-z_$][0-9A-Za-z_$]*$/.test(c))return ContentService.createTextOutput(`${c}(${j});`).setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(j).setMimeType(ContentService.MimeType.JSON)}
