const CONFIG={business:"Aquí podría ir el nombre de tu consultorio",address:"Aquí podría ir tu ubicación",mapUrl:"Aquí podría ir el enlace de tu ubicación",bank:"Aquí podrían ir tus datos bancarios",storage:"demoFisioAppointments"};
const AGENDA_ROOT=window.__agendaRoot||document;
if(window.__agendaClose)AGENDA_ROOT.querySelectorAll('.brand,.back-site-link,.embedded-back').forEach(link=>link.onclick=event=>{event.preventDefault();window.__agendaClose()});
const SERVICES=[{id:"assessment_initial",area:"hands",name:"Valoración inicial"},{id:"assessment_followup",area:"hands",name:"Consulta de seguimiento"},{id:"assessment_functional",area:"hands",name:"Evaluación funcional y postural"},{id:"therapy_musculoskeletal",area:"feet",name:"Fisioterapia musculoesquelética"},{id:"therapy_sports",area:"feet",name:"Rehabilitación deportiva"},{id:"therapy_postoperative",area:"feet",name:"Rehabilitación postoperatoria"},{id:"therapy_neurological",area:"feet",name:"Fisioterapia neurológica"},{id:"therapy_geriatric",area:"feet",name:"Fisioterapia geriátrica"},{id:"therapy_manual",area:"feet",name:"Terapia manual"},{id:"therapy_massage",area:"feet",name:"Masaje terapéutico"},{id:"therapy_dry_needling",area:"feet",name:"Punción seca"},{id:"therapy_home",area:"feet",name:"Rehabilitación a domicilio"}];
const WEEKDAY_TIMES=["10:30","12:30","16:00","18:00"],SATURDAY_TIMES=["10:00","11:30"];
const RETENTION_MONTHS=12;
const $=selector=>AGENDA_ROOT.querySelector(selector),$$=selector=>[...AGENDA_ROOT.querySelectorAll(selector)];
const pad=n=>String(n).padStart(2,"0");
const toISO=date=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const fromISO=value=>{const [y,m,d]=value.split("-").map(Number);return new Date(y,m-1,d)};
const phone=value=>String(value||"").replace(/\D/g,"");
const money=value=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(Number(value)||0);
const escapeHTML=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const getService=id=>SERVICES.find(item=>item.id===id)||{name:"Servicio"};
const legacyServices=item=>{if(Array.isArray(item.services)&&item.services.length)return item.services;const result=[];if(item.area==="both"){if(item.serviceId)result.push({id:item.serviceId,area:"hands",mode:item.mode||"",finish:item.finish||""});if(item.feetServiceId)result.push({id:item.feetServiceId,area:"feet",mode:item.feetMode||"",finish:item.feetFinish||""})}else if(item.serviceId)result.push({id:item.serviceId,area:item.area||getService(item.serviceId).area||"hands",mode:item.area==="feet"?item.feetMode||item.mode||"":item.mode||"",finish:item.area==="feet"?item.feetFinish||item.finish||"":item.finish||""});return result};
const serviceItemLabel=entry=>`${entry.area==="feet"?"Tratamiento":"Valoración"}: ${getService(entry.id).name}`;
const serviceLabel=item=>legacyServices(item).map(serviceItemLabel).join(" · ")||"Servicio";
function serviceOptions(area,selected=""){return SERVICES.filter(item=>item.area===area&&(item.selectable!==false||item.id===selected)).map(item=>`<option value="${item.id}"${item.id===selected?" selected":""}>${item.name}</option>`).join("")}
function serviceRow(entry={},index=0){const appointmentArea=$("#areaSelect").value,area=appointmentArea==="both"?(entry.area||"hands"):appointmentArea,id=entry.id&&getService(entry.id).area===area?entry.id:"",areaControl=appointmentArea==="both"?`<label>Tipo<select class="row-area"><option value="hands"${area==="hands"?" selected":""}>Valoración</option><option value="feet"${area==="feet"?" selected":""}>Tratamiento</option></select></label>`:`<input class="row-area" type="hidden" value="${area}"><label>Tipo<input value="${area==="feet"?"Tratamiento":"Valoración"}" disabled></label>`;return `<div class="service-row" data-service-row>${areaControl}<label>Servicio<select class="row-service" required>${serviceOptions(area,id)}</select></label><label class="row-mode-wrap" hidden>Modalidad<select class="row-mode"><option value=""></option></select></label><label class="row-finish-wrap" hidden>Detalle<select class="row-finish"><option value=""></option></select></label><button class="remove-service" type="button" aria-label="Quitar servicio">Quitar</button></div>`}
function addServiceRow(entry={}){const wrap=$("#serviceRows"),box=document.createElement("div");box.innerHTML=serviceRow(entry,wrap.children.length);const row=box.firstElementChild;wrap.append(row);updateServiceRow(row);if(entry.mode)row.querySelector(".row-mode").value=entry.mode;if(entry.finish)row.querySelector(".row-finish").value=entry.finish;refreshRemoveButtons()}
function refreshRemoveButtons(){$$("#serviceRows [data-service-row]").forEach((row,index,rows)=>row.querySelector(".remove-service").disabled=rows.length===1)}
function resetServiceRows(entries=[]){$("#serviceRows").innerHTML="";(entries.length?entries:[{area:$("#areaSelect").value==="feet"?"feet":"hands"}]).forEach(addServiceRow)}
function updateServiceRow(row){const area=row.querySelector(".row-area").value,select=row.querySelector(".row-service"),selected=select.value;select.innerHTML=serviceOptions(area,getService(selected).area===area?selected:"");row.querySelector(".row-mode-wrap").hidden=true;row.querySelector(".row-finish-wrap").hidden=true}
function collectServiceRows(){return $$("#serviceRows [data-service-row]").map(row=>({id:row.querySelector(".row-service").value,area:row.querySelector(".row-area").value,mode:"",finish:""})).filter(entry=>entry.id)}
let selectedDate=new Date();
let activeMessageAppointmentId="";
let activeSummaryPeriod="week";

function getAppointments(){try{return JSON.parse(localStorage.getItem(CONFIG.storage))||[]}catch{return[]}}
function saveAppointments(items){const before=getAppointments(),beforeById=new Map(before.map(item=>[item.id,item])),afterIds=new Set(items.map(item=>item.id));localStorage.setItem(CONFIG.storage,JSON.stringify(items));items.forEach(item=>{const old=beforeById.get(item.id);if(!old||old.updatedAt!==item.updatedAt)window.CloudAppointments?.upsert(item).catch(()=>{})});before.forEach(item=>{if(!afterIds.has(item.id))window.CloudAppointments?.remove(item.id).catch(()=>{})})}
function retentionCutoffISO(){const cutoff=new Date();cutoff.setMonth(cutoff.getMonth()-RETENTION_MONTHS);return toISO(cutoff)}
function isCurrentAppointment(item){return !item?.date||item.date>=retentionCutoffISO()}
function pruneLocalAppointments(){const current=getAppointments().filter(isCurrentAppointment);saveAppointments(current);return current}
function backupCountText(count){return `${count} ${count===1?"cita guardada":"citas guardadas"}`}
function downloadBackup(){const appointments=getAppointments(),payload={app:"Agenda demo",version:1,exportedAt:new Date().toISOString(),appointments},blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`agenda-demo-respaldo-${toISO(new Date())}.json`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("Respaldo descargado")}
function validBackupAppointment(item){return item&&typeof item==="object"&&typeof item.name==="string"&&item.name.trim()&&phone(item.phone).length>=10&&/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&timesForDate(item.date).includes(item.time)&&typeof item.serviceId==="string"}
async function restoreBackup(file){const error=$("#backupError");error.textContent="";try{const parsed=JSON.parse(await file.text()),imported=Array.isArray(parsed)?parsed:parsed.appointments;if(!Array.isArray(imported))throw new Error("Formato inválido");const valid=imported.filter(validBackupAppointment).map(item=>({...item,id:item.id||uid(),name:item.name.trim(),phone:phone(item.phone),price:Math.max(0,Number(item.price)||0),deposit:Math.max(0,Number(item.deposit)||0)})).filter(isCurrentAppointment);if(!valid.length)throw new Error("Sin citas válidas");const merged=new Map(pruneLocalAppointments().map(item=>[item.id,item]));valid.forEach(item=>merged.set(item.id,item));const items=[...merged.values()];saveAppointments(items);$("#backupAppointmentCount").textContent=backupCountText(merged.size);render();toast(`${valid.length} ${valid.length===1?"cita recuperada":"citas recuperadas"}`)}catch{error.textContent="No pudimos leer este respaldo. Selecciona un archivo generado por esta agenda."}finally{$("#importBackupInput").value=""}}
function formatDate(iso,options={weekday:"long",day:"numeric",month:"long"}){return fromISO(iso).toLocaleDateString("es-MX",options)}
function formatTime(value){const [hours,minutes]=value.split(":").map(Number),period=hours<12?"a. m.":"p. m.",hour=hours%12||12;return `${hour}:${pad(minutes)} ${period}`}
function timesForDate(iso){const day=fromISO(iso).getDay();return day===6?SATURDAY_TIMES:day>=1&&day<=5?WEEKDAY_TIMES:[]}
function isWorkingDay(iso){return timesForDate(iso).length>0}
function nextWorkingDate(date){const result=new Date(date);while(result.getDay()===0)result.setDate(result.getDate()+1);return result}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function waLink(number,message){const digits=phone(number),international=digits.length===10?`52${digits}`:digits;return `https://wa.me/${international}?text=${encodeURIComponent(message)}`}
function openWhatsApp(number,message){window.open(waLink(number,message),"_blank","noopener,noreferrer")}
function appointmentsFor(date){return getAppointments().filter(item=>item.date===date).sort((a,b)=>a.time.localeCompare(b.time))}
function availableTimes(date,ignoreId=""){const scheduled=timesForDate(date);if(!scheduled.length)return[];const occupied=getAppointments().filter(item=>item.date===date&&item.id!==ignoreId).map(item=>item.time);return scheduled.filter(time=>!occupied.includes(time))}
function summaryDates(period){const start=new Date(selectedDate),end=new Date(selectedDate);if(period==="month"){start.setDate(1);end.setMonth(end.getMonth()+1,0)}else{const mondayOffset=(start.getDay()+6)%7;start.setDate(start.getDate()-mondayOffset);end.setTime(start.getTime());end.setDate(end.getDate()+6)}return{start,end}}
function summaryItems(period){const{start,end}=summaryDates(period),startISO=toISO(start),endISO=toISO(end);return getAppointments().filter(item=>item.date>=startISO&&item.date<=endISO).sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`))}
function renderSummary(period=activeSummaryPeriod){activeSummaryPeriod=period;const items=summaryItems(period),{start,end}=summaryDates(period),income=items.reduce((total,item)=>total+(Number(item.price)||0),0),deposits=items.reduce((total,item)=>total+(Number(item.deposit)||0),0),balance=items.reduce((total,item)=>total+Math.max((Number(item.price)||0)-(Number(item.deposit)||0),0),0);$$("[data-summary-period]").forEach(button=>button.classList.toggle("active",button.dataset.summaryPeriod===period));$("#summaryRange").textContent=period==="month"?start.toLocaleDateString("es-MX",{month:"long",year:"numeric"}):`${start.toLocaleDateString("es-MX",{day:"numeric",month:"long"})} — ${end.toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"})}`;$("#summaryAppointments").textContent=items.length;$("#summaryIncome").textContent=money(income);$("#summaryDeposits").textContent=money(deposits);$("#summaryBalance").textContent=money(balance);$("#summaryList").innerHTML=items.length?items.map(item=>`<article class="summary-entry"><time>${escapeHTML(formatDate(item.date,{weekday:"short",day:"numeric",month:"short"}))}<small>${escapeHTML(formatTime(item.time))}</small></time><div><strong>${escapeHTML(item.name)}</strong><small>${escapeHTML(serviceLabel(item))}</small></div><strong>${money(item.price)}</strong></article>`).join(""):`<div class="summary-empty">No hay citas registradas en este periodo.</div>`}

function render(){const iso=toISO(selectedDate),items=appointmentsFor(iso),todayISO=toISO(new Date()),income=items.reduce((total,item)=>total+(Number(item.price)||0),0);$("#datePicker").value=iso;$("#dateTitle").textContent=formatDate(iso,{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("#appointmentCount").textContent=items.length;$("#dayIncome").textContent=money(income);const now=`${pad(new Date().getHours())}:${pad(new Date().getMinutes())}`,upcoming=items.find(item=>iso!==todayISO||item.time>=now);$("#nextTime").textContent=upcoming?formatTime(upcoming.time):"—";$("#appointmentList").innerHTML=items.length?items.map(cardTemplate).join(""):`<div class="empty-state"><span>♡</span><strong>Tu día está libre</strong><p>No hay citas registradas para esta fecha.</p><button class="secondary-btn" data-new>Crea una cita</button></div>`}
function cardTemplate(item){const deposit=Number(item.deposit)||0;return `<article class="appointment-item"><div class="appointment-time">${escapeHTML(formatTime(item.time))}<small>${item.time<"12:00"?"mañana":item.time<"18:00"?"tarde":"noche"}</small></div><span class="service-line"></span><div class="appointment-info"><h3>${escapeHTML(item.name)}</h3><p>${escapeHTML(serviceLabel(item))} · ${escapeHTML(item.phone)}</p><p>${item.notes?escapeHTML(item.notes):"Sin notas"}</p></div><div class="appointment-meta"><div class="appointment-amount"><span class="price">${money(item.price)}</span>${deposit?`<small>Anticipo: ${money(deposit)}</small>`:""}</div><button class="message-btn" data-message="${item.id}">WhatsApp</button><button class="more-btn" data-edit="${item.id}">Editar</button></div></article>`}
function fillTimes(date,selected="",ignoreId=""){let times=availableTimes(date,ignoreId);if(selected&&!times.includes(selected))times=[...times,selected].sort();$("#appointmentTime").innerHTML=times.length?times.map(time=>`<option value="${time}"${time===selected?" selected":""}>${formatTime(time)}</option>`).join(""):`<option value="">${isWorkingDay(date)?"Sin horarios disponibles":"No se trabaja los domingos"}</option>`}
function openNewAppointment(){const appointmentDay=nextWorkingDate(selectedDate),iso=toISO(appointmentDay);$("#appointmentForm").reset();$("#appointmentId").value="";$("#formEyebrow").textContent="Nueva cita";$("#formTitle").textContent="Agendar cita";$("#appointmentDate").value=iso;$("#deleteBtn").hidden=true;$("#formError").textContent="";$("#areaSelect").value="hands";resetServiceRows([{id:"assessment_initial",area:"hands",mode:"",finish:""}]);fillTimes(iso);$("#appointmentDialog").showModal()}
function openEditAppointment(id){const item=getAppointments().find(entry=>entry.id===id);if(!item)return;const services=legacyServices(item),areas=new Set(services.map(entry=>entry.area)),area=areas.size>1?"both":areas.has("feet")?"feet":"hands";$("#appointmentId").value=item.id;$("#clientName").value=item.name;$("#clientPhone").value=item.phone;$("#areaSelect").value=area;resetServiceRows(services);$("#appointmentDate").value=item.date;$("#appointmentPrice").value=item.price||"";$("#appointmentDeposit").value=item.deposit||"";$("#appointmentNotes").value=item.notes||"";$("#formEyebrow").textContent="Editar cita";$("#formTitle").textContent=item.name;$("#deleteBtn").hidden=false;$("#formError").textContent="";fillTimes(item.date,item.time,item.id);$("#appointmentDialog").showModal()}
function saveAppointment(event){event.preventDefault();const id=$("#appointmentId").value,name=$("#clientName").value.trim(),number=phone($("#clientPhone").value),area=$("#areaSelect").value,date=$("#appointmentDate").value,time=$("#appointmentTime").value,services=collectServiceRows(),price=Math.max(0,Number($("#appointmentPrice").value)||0),deposit=Math.max(0,Number($("#appointmentDeposit").value)||0),error=$("#formError"),items=getAppointments(),current=items.find(item=>item.id===id),wasRescheduled=Boolean(current&&(current.date!==date||current.time!==time)),reschedules=(Number(current?.reschedules)||0)+(wasRescheduled?1:0),first=services[0]||{},firstHand=services.find(entry=>entry.area==="hands"),firstFoot=services.find(entry=>entry.area==="feet");if(date&&!isWorkingDay(date)){error.textContent="Solo se pueden agendar citas de lunes a sábado.";return}if(!name||number.length<10||!date||!time||!services.length){error.textContent="Completa el nombre, un WhatsApp válido, al menos un servicio, fecha y hora.";return}if(area==="both"&&(!firstHand||!firstFoot)){error.textContent="Agrega por lo menos un servicio de manos y uno de pies.";return}if(deposit>price&&price>0){error.textContent="El anticipo no puede ser mayor que el precio acordado.";return}if(reschedules>2){error.textContent="Esta cita ya alcanzó el máximo de dos reprogramaciones.";return}if(!availableTimes(date,id).includes(time)){error.textContent="Ese horario ya está ocupado. Elige otro, por favor.";fillTimes(date,"",id);return}const record={...current,id:id||uid(),name,phone:number,area,services,serviceId:first.id,feetServiceId:firstFoot?.id||"",mode:firstHand?.mode||"",finish:firstHand?.finish||"",feetMode:firstFoot?.mode||"",feetFinish:firstFoot?.finish||"",date,time,price,deposit,status:current?.status||"Programada",reschedules,notes:$("#appointmentNotes").value.trim(),createdAt:current?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const updatedItems=id?items.map(item=>item.id===id?record:item):[...items,record];saveAppointments(updatedItems);selectedDate=fromISO(date);$("#appointmentDialog").close();render();toast(id?"Cita actualizada":"Cita guardada")}
function deleteAppointment(){const id=$("#appointmentId").value;if(!id||!confirm("¿Quieres cancelar y eliminar esta cita?"))return;saveAppointments(getAppointments().filter(item=>item.id!==id));$("#appointmentDialog").close();render();toast("Cita cancelada")}
function financialMessage(item){const price=Number(item.price)||0,deposit=Number(item.deposit)||0,details=[];if(price)details.push(`💵 Precio acordado: ${money(price)}`);if(deposit)details.push(`💳 Anticipo recibido: ${money(deposit)}`);if(price&&deposit)details.push(`💰 Saldo pendiente: ${money(Math.max(price-deposit,0))}`);return details.length?`\n${details.join("\n")}`:""}
function confirmationMessage(item){return `¡Hola, ${item.name}! 💖\n\nTu cita en ${CONFIG.business} está confirmada:\n\n📅 ${formatDate(item.date,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}\n🕐 ${formatTime(item.time)}\n✨ ${serviceLabel(item)}${financialMessage(item)}\n\n📍 ${CONFIG.address}\n🗺️ Ubicación: ${CONFIG.mapUrl}\n\nTe recordamos nuestras políticas:\n• Para cancelar o reagendar, avísanos con al menos 48 horas de anticipación.\n• Después de 10 minutos de retraso, la cita será cancelada y el anticipo no será reembolsable.\n• Los anticipos no son reembolsables; avisando con al menos 48 horas de anticipación, pueden conservarse para una nueva fecha.\n• Una cita puede reagendarse un máximo de dos veces.\n\n¡Gracias por elegirnos! Te esperamos ✨`}
function reminderMessage(item){return `¡Hola, ${item.name}! 💖\n\nTe recordamos tu próxima cita en ${CONFIG.business}:\n\n📅 ${formatDate(item.date,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}\n🕐 ${formatTime(item.time)}\n✨ ${serviceLabel(item)}${financialMessage(item)}\n\n📍 ${CONFIG.address}\n🗺️ ${CONFIG.mapUrl}\n\nSi necesitas hacer algún cambio, avísanos con al menos 48 horas de anticipación. ¡Te esperamos!`}
function cancellationMessage(item){return `Hola, ${item.name}. Te informamos que tu cita en ${CONFIG.business} del ${formatDate(item.date,{weekday:"long",day:"numeric",month:"long",year:"numeric"})} a las ${formatTime(item.time)} ha sido cancelada.\n\nSi deseas elegir una nueva fecha, con gusto podemos ayudarte a reagendar. 💖`}
function openMessageDialog(item){activeMessageAppointmentId=item.id;$("#messageDialogTitle").textContent=`Mensaje para ${item.name}`;$("#messageDialog").showModal()}

$("#todayText").textContent=new Date().toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
$("#areaSelect").value="hands";resetServiceRows([{id:"assessment_initial",area:"hands",mode:"",finish:""}]);
$("#newAppointmentBtn").onclick=openNewAppointment;$("#appointmentForm").onsubmit=saveAppointment;$("#deleteBtn").onclick=deleteAppointment;
$("#appointmentList").onclick=event=>{const add=event.target.closest("[data-new]"),edit=event.target.closest("[data-edit]"),message=event.target.closest("[data-message]");if(add)openNewAppointment();if(edit)openEditAppointment(edit.dataset.edit);if(message){const item=getAppointments().find(entry=>entry.id===message.dataset.message);if(item)openMessageDialog(item)}};
$("#messageDialog").onclick=event=>{const option=event.target.closest("[data-message-type]");if(!option)return;const item=getAppointments().find(entry=>entry.id===activeMessageAppointmentId);if(!item){$("#messageDialog").close();toast("No encontramos esa cita");return}const messages={confirmation:confirmationMessage,reminder:reminderMessage,cancellation:cancellationMessage},buildMessage=messages[option.dataset.messageType];if(!buildMessage)return;openWhatsApp(item.phone,buildMessage(item));$("#messageDialog").close()};
$("#appointmentDate").onchange=()=>fillTimes($("#appointmentDate").value,"",$("#appointmentId").value);
$("#addServiceBtn").onclick=()=>addServiceRow({area:$("#areaSelect").value==="feet"?"feet":"hands"});
$("#areaSelect").onchange=()=>resetServiceRows([{area:$("#areaSelect").value==="feet"?"feet":"hands"}]);
$("#serviceRows").onclick=event=>{const remove=event.target.closest(".remove-service");if(remove&&!remove.disabled){remove.closest("[data-service-row]").remove();refreshRemoveButtons()}};
$("#serviceRows").onchange=event=>{const row=event.target.closest("[data-service-row]");if(row&&(event.target.matches(".row-area")||event.target.matches(".row-service")))updateServiceRow(row)};
$("#previousDay").onclick=()=>{selectedDate.setDate(selectedDate.getDate()-1);render()};$("#nextDay").onclick=()=>{selectedDate.setDate(selectedDate.getDate()+1);render()};$("#todayBtn").onclick=()=>{selectedDate=new Date();render()};$("#datePicker").onchange=()=>{selectedDate=fromISO($("#datePicker").value);render()};
$("#paymentBtn").onclick=()=>{$("#paymentForm").reset();$("#paymentDialog").showModal()};$("#policiesBtn").onclick=()=>$("#policiesDialog").showModal();
$("#summaryBtn").onclick=()=>{activeSummaryPeriod="week";renderSummary("week");$("#summaryDialog").showModal()};
$("#summaryDialog").onclick=event=>{const periodButton=event.target.closest("[data-summary-period]");if(periodButton)renderSummary(periodButton.dataset.summaryPeriod)};
$("#backupBtn").onclick=()=>{$("#backupAppointmentCount").textContent=backupCountText(getAppointments().length);$("#backupError").textContent="";$("#importBackupInput").value="";$("#backupDialog").showModal()};
$("#exportBackupBtn").onclick=downloadBackup;
$("#importBackupInput").onchange=event=>{const[file]=event.target.files;if(file)restoreBackup(file)};
$("#paymentForm").onsubmit=event=>{event.preventDefault();const number=phone($("#paymentPhone").value);if(number.length<10){toast("Escribe un WhatsApp válido");return}openWhatsApp(number,`Hola! Buen día ☀️\n\nTe compartimos los datos para transferencia de ${CONFIG.business}\n\n${CONFIG.bank}\n\nCuando realices tu transferencia, por favor envíanos tu comprobante. Gracias 💖`);$("#paymentDialog").close()};
$$('[data-close-dialog]').forEach(button=>button.onclick=()=>button.closest("dialog").close());pruneLocalAppointments();render();window.refreshAgenda=render;window.CloudAppointments?.hydrate(items=>localStorage.setItem(CONFIG.storage,JSON.stringify(items))).then(()=>render());
